# Generated by Django 6.0.6 on 2026-07-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha de la medición', unique=True)),
                ('nps', models.FloatField(default=0.0, help_text='Net Promoter Score')),
                ('adr', models.DecimalField(decimal_places=2, default=0.0, help_text='Average Daily Rate', max_digits=10)),
                ('goppar', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross Operating Profit Per Available Room', max_digits=10)),
                ('revpar', models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue Per Available Room', max_digits=10)),
                ('trevpar', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Revenue Per Available Room', max_digits=10)),
                ('gop', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross Operating Profit', max_digits=15)),
                ('los', models.FloatField(default=0.0, help_text='Length of Stay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
