# Generated by Django 6.0.6 on 2026-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha de la transacción/estadía')),
                ('channel', models.CharField(help_text='Canal de venta (ej. OTA, Directo, Agencia)', max_length=50)),
                ('room_type', models.CharField(help_text='Tipo de Habitación (ej. Suite, Standard)', max_length=50)),
                ('segment', models.CharField(help_text='Segmento del cliente (ej. Leisure, Corporate)', max_length=50)),
                ('adr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revpar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('room_nights', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
