# Generated by Django 6.0.6 on 2026-07-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0004_surveyresponse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_perfil', models.CharField(default='Standard', max_length=100)),
                ('rendimiento_nps', models.FloatField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleados_avatars/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='surveys.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_global', models.IntegerField()),
                ('resolucion_pct', models.IntegerField()),
                ('analisis_pct', models.IntegerField()),
                ('empatia_pct', models.IntegerField()),
                ('rol_evaluado', models.CharField(max_length=100)),
                ('feedback_generado', models.TextField(blank=True, null=True)),
                ('proxima_evaluacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='hr.empleado')),
            ],
        ),
    ]
