# Generated by Django 6.0.6 on 2026-06-25 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0002_surveyresponse_survey_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('BOOKING', 'Booking.com'), ('TRIPADVISOR', 'TripAdvisor'), ('EXPEDIA', 'Expedia'), ('GOOGLE', 'Google Reviews')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_rating', models.DecimalField(decimal_places=1, default=10.0, max_digits=3)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=150, null=True)),
                ('posted_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_reviews', to='surveys.hotel')),
            ],
        ),
    ]
