# Generated by Django 6.0.6 on 2026-06-25 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_origin',
            field=models.CharField(choices=[('ONSITE', 'En Sitio (Código QR)'), ('FOLLOWUP', 'Post-estadía (Email)')], default='FOLLOWUP', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='guest_stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='surveys.gueststay'),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.department')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.qrcode'),
        ),
    ]
