# Generated by Django 6.0.6 on 2026-06-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyresponse_survey_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='VADER compound score from -1.0 to 1.0', null=True),
        ),
    ]
