# Generated by Django 6.0.6 on 2026-07-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveyresponse_sentiment_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevas (Bandeja de Entrada)'), ('REVIEW', 'Bajo Revisión'), ('ACTION_REQUIRED', 'Acción Requerida'), ('RESOLVED', 'Resueltas')], default='NEW', max_length=20),
        ),
    ]
